version: '3'
services:
  # frontend:
  #   image: adeliu42/gpass-frontend:latest
  #   ports:
  #     - "3000:3000"
  backend:
    image: adeliu42/gpass-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./backend/logs:/app/logs
    # env_file:
    #   - ./backend/.env
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      # - frontend
      - backend
