openapi: 3.0.0
info:
  title: GPASS API
  version: 1.0.0
  description: |-
    This is the API documentation for the GPASS project.
  contact:
    email: hahaisme@haha.WhySoSerious

tags:
  - name: exams
    description: Everything about your exams

paths:
  /api/1.0/exams/upload:
    post:
      tags:
        - exams
      summary: Upload exams
      description: Use this request to upload exams
      operationId: uploadExams
      requestBody:
        description: Exam object that needs to be uploaded
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                className:
                  type: string
                  description: The class name of the exam
                grade:
                  type: string
                  description: The grade of the exam
                type:
                  type: string
                  description: The type of the exam
                year:
                  type: string
                  description: The year of the exam
                teacher:
                  type: string
                  description: The teacher of the exam
                main_file:
                  type: string
                  format: binary
                  description: The main image of the product
                ans_file:
                  type: string
                  format: binary
                  description: The images of the product
                sheet_files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: The images of the product
                has_ans:
                  type: boolean
                  description: Whether the exam has answer
                  example: true
              required:
                - type
                - year
                - teacher
                - main_file
                - has_ans

      responses:
        "200":
          description: Product added successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: string
                description: The error message
              example:
                message: Bad request
        "415":
          description: No file uploaded
          content:
            application/json:
              schema:
                type: string
                description: The error message
              example:
                message: Please upload a file
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
                description: The error message
              example:
                message: Internal server error
  /api/1.0/exams/{classId}:
    get:
      tags:
        - exams
      summary: Get exams
      description: Use this request to get exams
      operationId: getExams
      parameters:
        - name: classId
          in: path
          description: The class ID
          required: true
          schema:
            type: string
          example: 1
        - name: paging
          in: query
          description: The paging of the search result
          required: false
          schema:
            type: integer
            format: int64
            default: null
      responses:
        "200":
          description: Exams retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Exam"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: string
                description: The error message
              example:
                message: Bad request
        "404":
          description: Class not found
          content:
            application/json:
              schema:
                type: string
                description: The error message
              example:
                message: Class not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
                description: The error message
              example:
                message: Internal server error
  
  /api/1.0/user/signup:
    post:
      tags:
        - user
      summary: Sign up
      description: Use this request to sign up
      operationId: signUp
      requestBody:
        description: User object that needs to be signed up
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the user
                email:
                  type: string
                  description: The email of the user
                password:
                  type: string
                  description: The password of the user
              required:
                - name
                - email
                - password
      responses:
        "200":
          description: User signed up successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: string
                description: The error message
              example:
                message: Bad request
        "409":
          description: Email already exists
          content:
            application/json:
              schema:
                type: string
                description: The error message
              example:
                message: Email already exists
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
                description: The error message
              example:
                message: Internal server error
  /api/1.0/user/signin:
    post:
      tags:
        - user
      summary: Sign in
      description: Use this request to sign in
      operationId: signIn
      requestBody:
        description: User object that needs to be signed in
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                provider:
                  type: string
                  description: The provider of the user
                email:
                  type: string
                  description: The email of the user
                password:
                  type: string
                  description: The password of the user
                access_token:
                  type: string
                  description: The access token of the user
              required:
                - provider
      responses:
        "200":
          description: User signed in successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: string
                description: The error message
              example:
                message: Bad request
        "403":
          description: Sign in failed
          content:
            application/json:
              schema:
                type: string
                description: The error message
              example:
                message: Email or password incorrect
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
                description: The error message
              example:
                message: Internal server error
  /api/1.0/user/profile:
    get:
      tags:
        - user
      summary: Get user profile
      description: Use this request to get user profile
      operationId: getprofile
      security:
        - bearerAuth: []
      parameters:
        - name: Authorization
          in: header
          description: The authorization token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
                description: The error message
              example:
                message: Token missing
        "403":
          description: Wrong token
          content:
            application/json:
              schema:
                type: string
                description: The error message
              example:
                message: Invalid token
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
                description: The error message
              example:
                message: Internal server error

components:
  schemas:
    Exam:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
          description: The exam ID
        type:
          type: string
          example: midterm
          description: The type of the exam
        teacher:
          type: string
          example: Haha
          description: The teacher of the exam
        year:
          type: string
          example: 2020
          description: The year of the exam
        rating_id:
          type: integer
          format: int64
          example: 1
          description: The rating ID of the exam
        main_file:
          type: string
          example: https://example.com/file.pdf
          description: The main file of the exam
        ans_file:
          type: string
          example: https://example.com/file.pdf
          description: The answer file of the exam
        sheet_files:
          type: array
          items:
            type: string
            example: https://example.com/file.pdf
          description: The sheet files of the exam
        has_ans:
          type: boolean
          example: true
          description: Whether the exam has answer
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
          description: The user ID
        provider:
          type: string
          example: facebook
          description: The provider of the user
        name:
          type: string
          example: Haha
          description: The name of the user
        email:
          type: string
          example: hahaisme@haha.whysoserious
          description: The email of the user
        picture:
          type: string
          example: https://example.com/image.jpg
          description: The picture of the user
    UserProfile:
      type: object
      properties:
        provider:
          type: string
          example: facebook
          description: The provider of the user
        name:
          type: string
          example: Haha
          description: The name of the user
        email:
          type: string
          example: hahaisme@haha.whysoserious
          description: The email of the user
        picture:
          type: string
          example: https://example.com/image.jpg
          description: The picture of the user
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
