name: Docker Workflow

on:
  push:
    branches:
      - main

env:
  DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker frontend image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/gpass-frontend:latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/gpass-backend:latest

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
    - name: SSH into EC2 Instance and pull Docker Image
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ${{ secrets.EC2_APP_PATH }}/GPASS
          git pull
          docker-compose pull
          docker-compose down
          docker-compose up -d
          docker-compose ps